### PR TITLE
Custom Metadata inside health state

### PR DESCRIPTION
**Pull request by povils**
Add custom Metadata to Health State (solves #1071)

### CODE REVIEW

**Comment by integrii** [comment]
You did a lot of great stuff here, and thank you for that!  I feel like a prefixed environment variable might be a little messy and confusing to implement.  What do you think about implementing these variables instead as a map in the `configmap`?

The `configmap` is [here](https://github.com/kuberhealthy/kuberhealthy/blob/master/cmd/kuberhealthy/config.go#L14).  We could put a `map[string]string` in here that gets placed in the status page output if present.  That would avoid all the prefix parsing and the slightly confusing pattern of prefixing your metadata as environment variables.

Thoughts?

**Comment by povils** [comment]
@integrii I think it is indeed better, I updated the PR :)

**Review by integrii — APPROVED** [review]
LGTM!  Sorry for the delay!  Thank you! 🎉

**Comment by fungaren** [comment]
How about report by `/externalCheckStatus`:

https://github.com/kuberhealthy/kuberhealthy/blob/b489fb6fba14ec054fddc1cf18d0f29658cec6cd/pkg/checks/external/status/main.go#L1-L26

Should we support to add metadata there?

**Comment by integrii** [comment]
Merged in #1158

**Pull request closed without merging**
